### ISSUE TITLE
Multiple messages via send_messages error

### ISSUE THREAD

**Issue by pagetribe** [messagemedia/messagemedia-ruby#4]
Still getting this error when running send_messages using messagemedia-soap 0.6.4
```Savon::SOAPFault: (SOAP-ENV:Client) The request is either not well-formed or is not valid against the relevant schema.
from /Users/mark/.rvm/gems/ruby-2.0.0-p481@ss32/gems/savon-2.8.0/lib/savon/response.rb:85:in `raise_soap_and_http_errors!'```

**Comment by tristanpenman** [comment]
Can you enable debug mode and attach a copy of the SOAP envelope that is produced by your code? Debug mode can be enabled by passing appending ":debug => true" to the arguments for Messagemedia::SOAP::Client.new() - e.g:

```
client = Messagemedia::SOAP::Client.new(YOUR_USERNAME, YOUR_PASSWORD, :debug => true)
```

**Comment by tristanpenman** [comment]
After some investigation, I discovered that the SDK was generating malformed XML for messages with more than one recipient due to a misunderstanding about how Savon handles object arrays. Version 0.6.5 of the messagemedia-soap gem should resolve the issue.

**Comment by tristanpenman** [comment]
@pagetribe, I will close this issue once you confirm that the issue has been resolved on your end.

**Comment by pagetribe** [comment]
I can confirm that this now works. Thanks.
